class Ctxkit < Formula
  include Language::Python::Virtualenv

  desc "Context portability and knowledge ingestion tool — bridge your markdown vault to any subscription LLM"
  homepage "https://github.com/piyush-tyagi-13/context-portability-tool"
  url "https://files.pythonhosted.org/packages/a3/39/2009dec8daf3b19a9deb66424274e7b4e081bd35b1a687558cf3b9c4278d/ctxkit_ai-1.2.0.tar.gz"
  sha256 "51a3863a34c585765ceb7b55a07a431f8123798d8ca5139b347b3edec72240d8"
  license "MIT"

  depends_on "python@3.12"

  # Core deps only. Backend extras installed via: ctxkit deps install
  resource "typer" do
    url "https://files.pythonhosted.org/packages/.../typer-0.12.0.tar.gz"
    sha256 "..."
  end

  # NOTE: Full resource list is auto-generated by:
  #   brew update-python-resources ctxkit.rb
  # Run this after updating the formula to regenerate all resource blocks.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "ctxkit", shell_output("#{bin}/ctxkit --help")
  end
end
